# Generated by Django 6.1.1 on 2026-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customerid", models.IntegerField()),
                ("customername", models.CharField(max_length=30)),
                ("customerphone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderid", models.IntegerField()),
                ("ordername", models.CharField(max_length=30)),
                ("orderprice", models.IntegerField()),
            ],
        ),
    ]
