# Generated by Django 6.1.1 on 2026-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Eno", models.IntegerField()),
                ("ename", models.CharField(max_length=40)),
                ("esal", models.FloatField()),
            ],
        ),
    ]
