# Generated by Django 6.1.1 on 2026-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="studentreg",
            fields=[
                (
                    "sid",
                    models.IntegerField(
                        max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("spassword", models.CharField(max_length=20)),
                ("sname", models.CharField(max_length=20)),
                ("sbranch", models.CharField(max_length=20)),
                ("semail", models.CharField(max_length=30)),
            ],
        ),
    ]
