# Generated by Django 6.1.1 on 2026-09-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                ("studentid", models.IntegerField(primary_key=True, serialize=False)),
                ("studentname", models.CharField(max_length=20)),
                ("studentbranch", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "username",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
            ],
        ),
    ]
